<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Detailed methods – Estimating the Economic Impacts of California’s Farm to School Incubator Grant Program</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../code/Appendix.01.data_cleaning_CAFTS.html" rel="next">
<link href="../code/issue_brief.html" rel="prev">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-87aed0b8589e23e45aa8556edf37a91b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../code/methods.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Detailed methods</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Estimating the Economic Impacts of California’s Farm to School Incubator Grant Program</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/FoodSystemsModeling/CAFarmToSchoolEconomicImpact" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/issue_brief.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Issue brief</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/methods.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Detailed methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/Appendix.01.data_cleaning_CAFTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Data Cleaning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../code/Appendix.02.summary_stats_objective1_CAFTS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Summary Statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#creating-a-farm-to-school-sector" id="toc-creating-a-farm-to-school-sector" class="nav-link active" data-scroll-target="#creating-a-farm-to-school-sector"><span class="header-section-number">2.1</span> Creating a Farm to School Sector</a></li>
  <li><a href="#estimating-the-shock" id="toc-estimating-the-shock" class="nav-link" data-scroll-target="#estimating-the-shock"><span class="header-section-number">2.2</span> Estimating the Shock</a></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model"><span class="header-section-number">2.3</span> Model</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">2.4</span> References</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">2.5</span> Appendix</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Detailed methods</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>To estimate the regional economic impacts associated with state investment in the Farm-to-School (F2S) Grant Program we used commercially available data from IMpact Analysis for PLANning (IMPLAN, 2024 Data Year),<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> an input-output model and the most commonly used tool for economic impact assessments <span class="citation" data-cites="miller_blair_2009">(<a href="methods.html#ref-miller_blair_2009" role="doc-biblioref">Miller and Blair 2009</a>)</span>. We augmented the model with interview data collected from F2S grant participants and from the Census of Agriculture.</p>
<p>Input-output models have been used to evaluate local food systems in many specific regions of the United States <span class="citation" data-cites="bauman_etal_2024 schmit_jablonski_2017">(e.g., <a href="methods.html#ref-bauman_etal_2024" role="doc-biblioref">Bauman et al. 2024</a>; <a href="methods.html#ref-schmit_jablonski_2017" role="doc-biblioref">Schmit and Jablonski 2017</a>)</span>. The accuracy of input-output studies are largely dependent on the production functions employed, especially in the sectors of interest, especially for the inputs of the sector of interest <span class="citation" data-cites="bauman_etal_2024 schmit_jablonski_2017">(<a href="methods.html#ref-bauman_etal_2024" role="doc-biblioref">Bauman et al. 2024</a>; <a href="methods.html#ref-schmit_jablonski_2017" role="doc-biblioref">Schmit and Jablonski 2017</a>)</span>. The customization of production functions has been central to numerous prior economic contribution and impact analyses, in which enterprise budgets or expenditure profile surveys serve as the basis for constructing tailored sectors <span class="citation" data-cites="bauman_etal_2024 koirala_etal_2020 leonard_watson_2011 schmit_jablonski_2017 thilmany_etal_2017">(e.g., <a href="methods.html#ref-bauman_etal_2024" role="doc-biblioref">Bauman et al. 2024</a>; <a href="methods.html#ref-koirala_etal_2020" role="doc-biblioref">Koirala et al. 2020</a>; <a href="methods.html#ref-leonard_watson_2011" role="doc-biblioref">Leonard and Watson 2011</a>; <a href="methods.html#ref-schmit_jablonski_2017" role="doc-biblioref">Schmit and Jablonski 2017</a>; <a href="methods.html#ref-thilmany_etal_2017" role="doc-biblioref">Thilmany et al. 2017</a>)</span>.</p>
<p>Research specifically related to local food systems has argued that the available sectors in IMPLAN do not accurately characterize local food systems, leading them to customize production functions to better represent this sector <span class="citation" data-cites="schmit_jablonski_2017 thilmany_etal_2017">(e.g., <a href="methods.html#ref-schmit_jablonski_2017" role="doc-biblioref">Schmit and Jablonski 2017</a>; <a href="methods.html#ref-thilmany_etal_2017" role="doc-biblioref">Thilmany et al. 2017</a>)</span>. We follow <span class="citation" data-cites="bauman_etal_2024">Bauman et al. (<a href="methods.html#ref-bauman_etal_2024" role="doc-biblioref">2024</a>)</span>, <span class="citation" data-cites="jablonski_etal_2016">Jablonski et al. (<a href="methods.html#ref-jablonski_etal_2016" role="doc-biblioref">2016</a>)</span>, and <span class="citation" data-cites="thilmany_etal_2017">Thilmany et al. (<a href="methods.html#ref-thilmany_etal_2017" role="doc-biblioref">2017</a>)</span> to create a F2S sector using customized production functions based on surveys of expenditure profiles. We use data collected from interviews of grant recipients to estimate average expenditure and spending profiles of the F2S sector and the restricted-access farm level 2022 Census of Agriculture data to estimate the total size of the sector.</p>
<section id="creating-a-farm-to-school-sector" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="creating-a-farm-to-school-sector"><span class="header-section-number">2.1</span> Creating a Farm to School Sector</h2>
<p>The first step of customizing a new sector is to understand the expenditure patterns in the sector (i.e., the production function). Figure 1 shows expenditure patterns of F2S grant participants. Labor is by far the largest expense, representing 53% of variable expenses. This is significantly higher than the traditional fruit and vegetable sectors in IMPLAN, which are closer to 14% and highlights the importance of creating a customized farm to school sector to accurately represent this group of farmers.</p>
<div>
<p><img src="../figures/variable_expense.png" class="img-fluid"></p>
<p>Figure 1. Variable expense categories as a percent of total variable expense<br>
<em>Source: Interviews of CA Farm-to-School grant participants</em></p>
</div>
<p><a href="#tbl-expenditure" class="quarto-xref">Table&nbsp;<span>2.1</span></a> describes how we bridged the categories of expenditure data collected in the interviews with IMPLAN sectors. Wherever possible, we used information from published case studies to inform the decisions described below <span class="citation" data-cites="jablonski_etal_2016 schmit_jablonski_2017 thilmany_etal_2016">(<a href="methods.html#ref-jablonski_etal_2016" role="doc-biblioref">Jablonski et al. 2016</a>; <a href="methods.html#ref-schmit_jablonski_2017" role="doc-biblioref">Schmit and Jablonski 2017</a>; <a href="methods.html#ref-thilmany_etal_2016" role="doc-biblioref">Thilmany et al. 2016</a>)</span> and used margins published by IMPLAN.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The Census of Agriculture sectors for livestock (breeding livestock purchased or leased, all other livestock and poultry purchased or leased) bridge to the IMPLAN sector “112 Animal Production and Aquaculture.” Custom work and custom hauling bridges to IMPLAN sector “115 Support Activities for Agriculture and Forestry.” Utilities purchased for the farm business bridges to IMPLAN sector “221 Utilities,” while hired farm and ranch labor and proprietor income bridge to IMPLAN sector “Employee Compensation” and “Proprietor Income,” respectively. We use the regional purchase coefficients from IMPLAN to estimate the proportion of margined expenditures that stay in the California economy. The IMPLAN values are very similar to what was reported in the interviews of FTS grant recipients and includes all sectors of interest.</p>
<div id="tbl-expenditure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-expenditure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Bridging Census of Agriculture expenditure data with IMPLAN sectors
</figcaption>
<div aria-describedby="tbl-expenditure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Census of Agriculture expenditure category</strong></th>
<th><strong>IMPLAN sector</strong></th>
<th><strong>Margin</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><em>Non-margined sectors</em></strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Breeding livestock purchased or leased; All other livestock and poultry purchased or leased</td>
<td>112 Animal Production and Aquaculture</td>
<td></td>
</tr>
<tr class="odd">
<td>Customwork and custom hauling</td>
<td>115 Support Activities for Agriculture and Forestry</td>
<td></td>
</tr>
<tr class="even">
<td>Utilities purchased for the farm business</td>
<td>221 Utilities</td>
<td></td>
</tr>
<tr class="odd">
<td>Hired farm and ranch labor</td>
<td>Employee Compensation</td>
<td></td>
</tr>
<tr class="even">
<td>Proprietor income</td>
<td>Proprietor Income</td>
<td></td>
</tr>
<tr class="odd">
<td><strong><em>Margined sectors</em></strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Feed purchased for livestock and poultry<sup>a</sup></td>
<td>111 Crop Production</td>
<td></td>
</tr>
<tr class="odd">
<td></td>
<td>42 Wholesale Trade</td>
<td></td>
</tr>
<tr class="even">
<td></td>
<td>444 Building Material and Garden Equipment and Supplies Dealers</td>
<td></td>
</tr>
<tr class="odd">
<td>Seeds, plants, vines, trees, etc. purchased<sup>b</sup></td>
<td>111 Crop Farming, 1112 Vegetable and Melon Farming, and 1113 Fruit Farming</td>
<td>42%</td>
</tr>
<tr class="even">
<td></td>
<td>42 Wholesale Trade</td>
<td>55%</td>
</tr>
<tr class="odd">
<td></td>
<td>484 Truck Transportation</td>
<td>4%</td>
</tr>
<tr class="even">
<td>Fertilizer, lime, and soil conditioners purchased; Chemicals purchased<sup>c</sup></td>
<td>325 Chemical Manufacturing</td>
<td>48%</td>
</tr>
<tr class="odd">
<td></td>
<td>42 Wholesale Trade</td>
<td>22%</td>
</tr>
<tr class="even">
<td></td>
<td>444 Building Material and Garden Equipment and Supplies Dealers</td>
<td>28%</td>
</tr>
<tr class="odd">
<td></td>
<td>484 Truck Transportation</td>
<td>3%</td>
</tr>
<tr class="even">
<td>Gasoline, fuels, and oils purchased for the farm business<sup>d</sup></td>
<td>324 Petroleum and Coal Production</td>
<td>63%</td>
</tr>
<tr class="odd">
<td></td>
<td>42 Wholesale Trade</td>
<td>19%</td>
</tr>
<tr class="even">
<td></td>
<td>457 Gasoline Stations</td>
<td>17%</td>
</tr>
<tr class="odd">
<td></td>
<td>484 Truck Transportation</td>
<td>2%</td>
</tr>
<tr class="even">
<td>Repairs, supplies, and maintenance costs for the farm business<sup>e</sup></td>
<td>23 Construction</td>
<td>40%</td>
</tr>
<tr class="odd">
<td></td>
<td>811 Repair and Maintenance</td>
<td>30%</td>
</tr>
<tr class="even">
<td></td>
<td>Employee Compensation</td>
<td>30%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><sup>a</sup> We assume operators are purchasing 80% of feed from wholesalers and 20% directly from other farmers.<br>
<sup>b</sup> We assume seeds, plants, vines, etc. are purchased directly from a wholesaler and the producing sectors for purchases in this category are crop farming, vegetable and melon farming, and fruit farming. The expenses are allocated between these three sectors based on the proportion of output in each sector. We average the margins for 111 Crop Farming (the margined commodity is grains), 1112 Vegetable and Melon Farming, and 1113 Fruit Farming as the producing sector and combine the retail and wholesale margins.<br>
<sup>c</sup> We assume 75% of fertilizers and chemicals are purchased directly from a wholesaler and the remaining 25% are purchased from a retailer. For those purchases made directly from the wholesaler, we sum the retail and wholesale margin for a resulting wholesale margin of 52%.<br>
<sup>d</sup> We assume 80% of fuel and oil purchases are made at the wholesale level on diesel, with the remaining 20% purchased at the retail level. For the 80% purchased wholesale, we sum the retail and wholesale margins for a resulting wholesale margin of 36%.<br>
<sup>e</sup> We allocate 60% of expenditures to 23 Construction, 20% to Employee Compensation, and the remaining 20% to 811 Repair and Maintenance.</p>
<p>After determining the average proportion of expenditures in each category, these values are scaled to reflect total sector-level spending. We estimate total sales from a “similar” set of farms in California using the restricted access 2022 Census of Agriculture and use that number to represent the total size of the farm to school sector. The “similar” set of farms is defined as those with less than $500,000 in sales, participate in at least 3 climate smart practices<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> and have the majority of their sales from fruits and vegetables. We estimate total sales in this sector of $22.6 million.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>The second step in sector customization involves analyzing sales patterns, i.e., who buys from the F2S sector. Our interviews capture total income and its breakdown across agricultural sales, government payments,<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> farm-related income,<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> and production contracts. Agricultural sales are further disaggregated by channel: direct-to-consumer, retail, institutional, and intermediate markets.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Figure 2 shows the percent of total income in each category for the total sector as reported in the interviews.</p>
<div>
<p><img src="../figures/pct_income_by_source.png" class="img-fluid"></p>
<p>Figure 2. Percent of total income by source (n = 21)</p>
<p><em>Source: Interviews of CA Farm-to-School grant participants</em><br>
<em>Notes: Income from production contracts is dropped from the figures as it represents less than 1% of total income. Farm related income includes custom work, rent, sales of forest products, agritourism, dividends from cooperatives, insurance payments, renting and leasing farm machinery, etc. Government payments include state, local and federal government payments. Direct-to-consumer market channels include farmers markets, on-farm stores or farm stands, roadside stands or stores, CSA (Community Supported Agriculture), online marketplaces, etc. Retail markets include supermarkets, supercenters, restaurants, caterers, independently owned grocery stores, food cooperatives, etc. Institutions include K-12 schools, colleges or universities, hospitals, workplace cafeterias, prisons, foodbanks, etc. Intermediate markets include businesses or organizations in the middle of the supply chain marketing locally- and/or regionally-branded products, such as distributors, food hubs, brokers, auction houses, wholesale and terminal markets, food processors, etc.</em></p>
</div>
<p>As we did with expenditures, when customizing the new F2S sector in IMPLAN, we need to translate our income categories into the appropriate IMPLAN sectors (<a href="#tbl-income" class="quarto-xref">Table&nbsp;<span>2.2</span></a>). We allocate direct-to-consumer sales equally across households with income of at least $100,000. Retail sales are allocated to food and beverage stores. Intermediate market sales are allocated between food manufacturing (25%) and wholesale trade (75%). Institutional sales are allocated equally between state and local government education and hospital and health services. We assume 25% of farm related income is from agritourism and allocate that proportion equally across households with income of at least $100,000. The remaining 75% is allocated equally across crop production, vegetable and melon farming, fruit farming, and animal production. We allocate income from production contracts to food manufacturing, assuming the fruit and vegetable processors are the mostly likely production contracts for this group of farmers. Government payments are slightly different because they are a transfer payment rather than a purchase of a good or service. In IMPLAN’s framework, we treat government farm payments as value-added income and allocate payments to other property type income.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>Government payments are allocated equally across Federal government non-defense, state/local government other, state/local government education, and state/local government hospitals and health services.</p>
<div id="tbl-income" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: Bridging Census of Agriculture income data with IMPLAN sectors
</figcaption>
<div aria-describedby="tbl-income-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Interview category</strong></th>
<th><strong>IMPLAN sector</strong></th>
<th><strong>Allocation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Direct-to-consumer sales</td>
<td>Households 100–150k</td>
<td>33%</td>
</tr>
<tr class="even">
<td></td>
<td>Households 150–200k</td>
<td>33%</td>
</tr>
<tr class="odd">
<td></td>
<td>Households GT200k</td>
<td>33%</td>
</tr>
<tr class="even">
<td>Retail sales</td>
<td>445 Food and Beverage Stores</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>Intermediate market sales</td>
<td>311 Food Manufacturing</td>
<td>25%</td>
</tr>
<tr class="even">
<td></td>
<td>42 Wholesale Trade</td>
<td>75%</td>
</tr>
<tr class="odd">
<td>Institutional sales</td>
<td>State/Local Govt Education</td>
<td>50%</td>
</tr>
<tr class="even">
<td></td>
<td>State/Local Govt Hospital &amp; Health Services</td>
<td>50%</td>
</tr>
<tr class="odd">
<td>Farm related income</td>
<td>Households 100–150k</td>
<td>8.3%</td>
</tr>
<tr class="even">
<td></td>
<td>Households 150–200k</td>
<td>8.3%</td>
</tr>
<tr class="odd">
<td></td>
<td>Households GT200k</td>
<td>8.3%</td>
</tr>
<tr class="even">
<td></td>
<td>111 Crop Production (not including 1112/1113)</td>
<td>18.8%</td>
</tr>
<tr class="odd">
<td></td>
<td>1112 Vegetable and melon farming</td>
<td>18.8%</td>
</tr>
<tr class="even">
<td></td>
<td>1113 Fruit farming</td>
<td>18.8%</td>
</tr>
<tr class="odd">
<td></td>
<td>112 Animal Production and Aquaculture</td>
<td>18.8%</td>
</tr>
<tr class="even">
<td>Production contracts</td>
<td>311 Food Manufacturing</td>
<td>100%</td>
</tr>
<tr class="odd">
<td>Government payments</td>
<td>Other Property Type Income</td>
<td>100%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Incorporating the F2S sector into the IMPLAN model does not expand the overall size of the economy; rather, it produces more precise data by better capturing the expenditure patterns generated by a distinct F2S sector — patterns that existing, more generalized IMPLAN sectors fail to fully reflect. The F2S sector was constructed from operations represented within the “Vegetable and Melon Farming” and “Fruit Farming” IMPLAN sectors. To prevent double counting, F2S expenditures and sales were subtracted from these two sectors proportionally, in accordance with IMPLAN’s existing expense allocations, ensuring accurate representation both within the new sector and across the broader aggregation of farm operations. When creating the new sector and estimating the economic impact, we use the regional purchase coefficients from IMPLAN to estimate the proportion of expenditures that stay in the California economy as they are similar to what was reported in the interviews of F2S grant recipients.</p>
<p>Another important consideration in economic impact studies is opportunity costs. Previous studies estimating the economic impact of increased spending in local food systems have acknowledged the need to consider opportunity costs (i.e., estimating how much an increase in sales to schools led to a decrease in sales through other market channels) <span class="citation" data-cites="hughes_etal_2008 jablonski_etal_2016 schmit_jablonski_2017 thilmany_etal_2017">(e.g., <a href="methods.html#ref-hughes_etal_2008" role="doc-biblioref">Hughes et al. 2008</a>; <a href="methods.html#ref-jablonski_etal_2016" role="doc-biblioref">Jablonski et al. 2016</a>; <a href="methods.html#ref-schmit_jablonski_2017" role="doc-biblioref">Schmit and Jablonski 2017</a>; <a href="methods.html#ref-thilmany_etal_2017" role="doc-biblioref">Thilmany et al. 2017</a>)</span>. We use data collected from interviews of grant recipients to estimate how increased sales to schools impacted sales through other market channels (Figure 3). Expanded production was the most frequently cited response with more than three-quarters of surveyed producers reporting increases to meet school demand. Few indicated pulling back from direct-to-consumer or intermediated channels, suggesting that farm to school markets tend to create new growth for participating farms rather than diverting products from existing buyers.</p>
<p><em>Figure 3. Responses to: How did the California Farm to School Incubator Grant affect sales and production to other markets? (n = 21)</em></p>
<p><em>Source: Interviews of CA Farm-to-School grant participants</em></p>
</section>
<section id="estimating-the-shock" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="estimating-the-shock"><span class="header-section-number">2.2</span> Estimating the Shock</h2>
<p>To estimate the shock of increased spending in the California economy resulting from F2S grants, we allocate FIG grant awards to different sectors of the economy. <a href="#tbl-awards" class="quarto-xref">Table&nbsp;<span>2.3</span></a> shows the awards by group and by the type of organization. The organization type is only available for Cohort 3, so we assume the same allocation when we have data on both cohorts. If there are two IMPLAN sectors associated with an award, it is allocated equally across the sectors.</p>
<div id="tbl-awards" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-awards-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.3: F2S grant awards by cohort and IMPLAN crosswalk
</figcaption>
<div aria-describedby="tbl-awards-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Level</strong></th>
<th><strong>Group</strong></th>
<th><strong>Total Awards</strong></th>
<th><strong>By org type for cohorts 2 &amp; 3</strong></th>
<th><strong>IMPLAN sector</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overall Total</td>
<td>Cohorts 2 &amp; 3</td>
<td>$25,444,967</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>By Cohort</td>
<td>Cohort 2</td>
<td>$6,824,488</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>By Cohort</td>
<td>Cohort 3</td>
<td>$18,620,479</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Org Type</td>
<td>Aggregator/Food Hub/Distributor</td>
<td>$1,157,223</td>
<td>$1,581,350</td>
<td>42 Wholesale Trade</td>
</tr>
<tr class="odd">
<td>Org Type</td>
<td>California Native American Tribe</td>
<td>$350,000</td>
<td>$478,277</td>
<td>State/Local Govt Other</td>
</tr>
<tr class="even">
<td>Org Type</td>
<td>Co-op/Food Hub</td>
<td>$699,782</td>
<td>$956,255</td>
<td>42 Wholesale Trade</td>
</tr>
<tr class="odd">
<td>Org Type</td>
<td>Farm + Aggregator/Food Hub</td>
<td>$1,747,520</td>
<td>$2,387,994</td>
<td>CA F2S and 42 Wholesale Trade</td>
</tr>
<tr class="even">
<td>Org Type</td>
<td>Farm + Distribution/Wholesale</td>
<td>$2,290,594</td>
<td>$3,130,107</td>
<td>CA F2S and 42 Wholesale Trade</td>
</tr>
<tr class="odd">
<td>Org Type</td>
<td>Farm Only</td>
<td>$12,025,414</td>
<td>$16,432,781</td>
<td>CA F2S</td>
</tr>
<tr class="even">
<td>Org Type</td>
<td>Other/Unique</td>
<td>$349,946</td>
<td>$478,203</td>
<td>CA F2S</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>Source: Food Insight Group (FIG)</em></p>
<p><em>Notes: Org type is only available for cohort 3, so we assume the same allocation when we have data on both cohorts. If two sectors, we allocate equally across sectors.</em></p>
<p>To model the “shock” associated with state investment in the program, based on the sector that received the funds (as shown in <a href="#tbl-awards" class="quarto-xref">Table&nbsp;<span>2.3</span></a>), we estimated net rather than gross effects. Where producers reported that school sales replaced other sales or reduced purchases from certain sectors, we incorporated offsetting negative shocks to avoid overstating the program’s economic impact. <a href="#tbl-output" class="quarto-xref">Table&nbsp;<span>2.4</span></a> shows the net “shock” in each sector including both the increase in sales to schools as well as the resulting decrease in sales to other sectors.</p>
<div id="tbl-output" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.4: Change in output by sector
</figcaption>
<div aria-describedby="tbl-output-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th><strong>Scenario 1 – Cohort 3 only</strong></th>
<th><strong>Scenario 2 – Cohorts 2 &amp; 3</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CA Farm to School</td>
<td>$14,394,417</td>
<td>$19,670,035</td>
</tr>
<tr class="even">
<td>42 Wholesale Trade</td>
<td>$3,871,062</td>
<td>$5,289,823</td>
</tr>
<tr class="odd">
<td>445 Food and Beverage Stores</td>
<td>($5,000)</td>
<td>($6,833)</td>
</tr>
<tr class="even">
<td>Households 100–150k</td>
<td>($13,333)</td>
<td>($18,220)</td>
</tr>
<tr class="odd">
<td>Households 150–200k</td>
<td>($13,333)</td>
<td>($18,220)</td>
</tr>
<tr class="even">
<td>Households GT200k</td>
<td>($13,333)</td>
<td>($18,220)</td>
</tr>
<tr class="odd">
<td>State/Local Govt Other</td>
<td>$350,000</td>
<td>$478,277</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="model" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="model"><span class="header-section-number">2.3</span> Model</h2>
<p>The SAM and associated tables can all be found in “../data_final/”</p>
</section>
<section id="references" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="references"><span class="header-section-number">2.4</span> References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-bauman_etal_2024" class="csl-entry" role="listitem">
Bauman, A., P. Watson, D. Thilmany, et al. 2024. <span>“Building
Representative State Groupings in an Input-Output Model for the
Development of an Economic Impact Calculator for Nutrition Incentive
Programs.”</span> <em>Economic Development Quarterly</em> 38 (4):
288–301. <a href="https://doi.org/10.1177/08912424241282425">https://doi.org/10.1177/08912424241282425</a>.
</div>
<div id="ref-hughes_etal_2008" class="csl-entry" role="listitem">
Hughes, D. W., C. Brown, S. Miller, and T. McConnell. 2008.
<span>“Evaluating the Economic Impact of Farmers’ Markets Using an
Opportunity Cost Framework.”</span> <em>Journal of Agricultural and
Applied Economics</em> 40 (1): 253–65.
</div>
<div id="ref-jablonski_etal_2016" class="csl-entry" role="listitem">
Jablonski, B. B. R., T. M. Schmit, and D. Kay. 2016. <span>“Assessing
the Economic Impacts of Food Hubs on Regional Economies: A Framework
That Includes Opportunity Cost.”</span> <em>Agricultural and Resource
Economics Review</em> 45 (1).
</div>
<div id="ref-koirala_etal_2020" class="csl-entry" role="listitem">
Koirala, S., P. Watson, C. McIntosh, and L. Dandurand. 2020.
<span>“Economic Impact of <span>Globodera Pallida</span> on the Idaho
Economy.”</span> <em>American Journal of Potato Research</em> 97 (2):
214–20. <a href="https://doi.org/10.1007/s12230-020-09768-2">https://doi.org/10.1007/s12230-020-09768-2</a>.
</div>
<div id="ref-leonard_watson_2011" class="csl-entry" role="listitem">
Leonard, J., and P. Watson. 2011. <em>Description of the Input-Output
Model for Pacific Coast Fisheries</em>. NOAA Technical Memorandum
NMFS-NWFSC-111. U.S. Department of Commerce, National Oceanic;
Atmospheric Administration National Marine Fisheries Service. <a href="https://repository.library.noaa.gov/view/noaa/8718/noaa_8718_DS1.pdf">https://repository.library.noaa.gov/view/noaa/8718/noaa_8718_DS1.pdf</a>.
</div>
<div id="ref-miller_blair_2009" class="csl-entry" role="listitem">
Miller, R. E., and P. D. Blair. 2009. <em>Input-Output Analysis:
Foundations and Extensions</em>. 2nd ed. Cambridge University Press.
</div>
<div id="ref-schmit_jablonski_2017" class="csl-entry" role="listitem">
Schmit, T. M., and B. B. R. Jablonski. 2017. <em>A Practitioner’s Guide
to Conducting an Economic Impact Assessment of Regional Food Hubs Using
<span>IMPLAN</span>: A Systematic Approach</em>. Extension Bulletin EB
2017-01. Cornell University.
</div>
<div id="ref-thilmany_etal_2016" class="csl-entry" role="listitem">
Thilmany, D., D. Conner, S. Deller, et al. 2016. <em>The Economics of
Local Food Systems: A Toolkit to Guide Community Discussions,
Assessments and Choices</em>. U.S. Department of Agriculture,
Agricultural Marketing Service. <a href="https://localfoodeconomics.com/toolkit/">https://localfoodeconomics.com/toolkit/</a>.
</div>
<div id="ref-thilmany_etal_2017" class="csl-entry" role="listitem">
Thilmany, D., D. Conner, S. Deller, et al. 2017. <em>The Economics of
Local Food Systems: A Toolkit to Guide Community Discussions,
Assessments and Choices</em>. U.S. Department of Agriculture,
Agricultural Marketing Service. <a href="https://localfoodeconomics.com/toolkit/">https://localfoodeconomics.com/toolkit/</a>.
</div>
</div>
</section>
<section id="appendix" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="appendix"><span class="header-section-number">2.5</span> Appendix</h2>
<p><strong>Climate smart practices crosswalk between Census of Agriculture and California Farm to School Cohort 2 Grantees</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Census of Agriculture</strong></th>
<th><strong>Cohort 2 Grantees</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Planted to a cover crop (cover crops are planted primarily for managing soil fertility, soil quality, and controlling weeds, pests, and diseases; excluding CRP acres)</td>
<td>Cover crop; Conservation Cover</td>
</tr>
<tr class="even">
<td>Utilized no till or reduced till practices</td>
<td>No till; Reduced till</td>
</tr>
<tr class="odd">
<td>Practice alley cropping, silvopasture, or forest farming, or have riparian forest buffers or windbreaks</td>
<td>Strip cropping; Hedgerow planting; Windbreak/Shelterbelt Establishment; Vegetative Barriers; Riparian Forest Buffer; Tree/Shrub Establishment; Riparian Herbaceous Cover</td>
</tr>
<tr class="even">
<td>Has acres of cropland and pastureland on which animal manure was applied</td>
<td>Compost</td>
</tr>
<tr class="odd">
<td>Practice rotational or management-intensive grazing</td>
<td>Prescribed grazing</td>
</tr>
<tr class="even">
<td>Organic (USDA NOP certified organic production, USDA NOP organic production exempt from certification, Acres transitioning into USDA NOP organic production, Production according to USDA NOP standards but NOT certified or exempt)</td>
<td>Certified organic; Transitioning organic; Non-certified organic; Pesticide free</td>
</tr>
<tr class="odd">
<td>Not matched</td>
<td>Nutrient management; Crop rotation; Crop-livestock integration; Grassed Waterway; Filter Strip; Rain catchment for irrigation</td>
</tr>
</tbody>
</table>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>All sectors are aggregated with the 528 base industry set with vegetable and melon farming and fruit farming disaggregated from the broader crop sector.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>When there are multiple producing sectors, we average margins. We combined margins for all transportation into 484 Truck Transportation.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>See appendix for more information on climate smart practices and how we bridged the data collected through surveys of F2S participants and Census of Agriculture data.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>For reference, this represents less than 1% of all local sales in California.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Government payments include state, local and federal government payments.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Farm related income includes custom work, rent, sales of forest products, agritourism, dividends from cooperatives, insurance payments, renting and leasing farm machinery, etc.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Direct-to-consumer market channels include farmers markets, on-farm stores or farm stands, roadside stands or stores, CSA (Community Supported Agriculture), online marketplaces, etc. Retail markets include supermarkets, supercenters, restaurants, caterers, independently owned grocery stores, food cooperatives, etc. Institutions include K-12 schools, colleges or universities, hospitals, workplace cafeterias, prisons, foodbanks, etc. Intermediate markets include businesses or organizations in the middle of the supply chain marketing locally- and/or regionally-branded products, such as distributors, food hubs, brokers, auction houses, wholesale and terminal markets, food processors, etc.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>This assumes government payments are returns to the farm operation rather than labor compensation.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../code/issue_brief.html" class="pagination-link" aria-label="Issue brief">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Issue brief</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../code/Appendix.01.data_cleaning_CAFTS.html" class="pagination-link" aria-label="Data Cleaning">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Data Cleaning</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>